version: "3"
services:
  metabase:
    image: metabase/metabase-enterprise:latest
    environment:
      - MB_PREMIUM_EMBEDDING_TOKEN=${MB_PREMIUM_EMBEDDING_TOKEN}
      - MB_ENABLE_EMBEDDING=true
      - MB_EMBEDDING_APP_ORIGIN=http://${HOST}:3001
      - MB_JWT_ENABLED=true
      - MB_JWT_IDENTITY_PROVIDER_URI=http://${HOST}:3001/api/auth/metabase
      - MB_JWT_SHARED_SECRET=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
      - MB_SAML_ENABLED=${MB_SAML_ENABLED}
      - MB_SAML_APPLICATION_NAME=${MB_SAML_APPLICATION_NAME}
      - MB_SAML_IDENTITY_PROVIDER_URI=${MB_SAML_IDENTITY_PROVIDER_URI}
      - MB_SAML_IDENTITY_PROVIDER_CERTIFICATE=${MB_SAML_IDENTITY_PROVIDER_CERTIFICATE}
    ports:
      - "3000:3000"
  metalbase:
    build: .
    environment:
      - PORT=3001
      - METABASE_URL=http://${HOST}:3000
      - METABASE_JWT_SHARED_SECRET=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ports:
      - "3001:3001"